# Generated by Django 3.1.6 on 2021-02-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbacapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
